ext {
    androidXVersion = '1.1.0'
    kotlinVersion = '1.3.70'
    coroutinesCoreKotlin = '1.3.5'
    supportLibraryVersion = '27.1.1'
    eventBusVersion = '3.0.0'
    okHttp3Version = '3.8.1'
    rxJava2Version = '2.1.7'
    rxAndroid2Version = '2.0.2'
    retrofitRx2AdapterVersion = '2.3.0'
    retrofit2Version = '2.3.0'
    glideVersion = '4.9.0'
    glideOkHttpVersion = '4.9.0'
    daggerVersion = '2.21'
    koinVersion = '2.0.0-GA'
    gsonVersion = '2.8.1'
    espressoCoreVersion = '2.2.2'
    constrainLayoutVersion = '1.1.2'
    deepLinkVersion = '3.1.0'
    ankoVersion = '0.10.5'
    multidexVersion = '1.0.1'
    rxBindingVersion = '2.0.0'
    playServiceVersion = '16.0.0'
    googlePlacesVersion = '1.1.0'
    mixpanelVersion = '5.1.4'
    leakCanaryVersion = '1.5.4'
    powerMockVersion = '1.7.3'
    jobDispatcherVersion = '0.8.5'
    animonStreamVersion = '1.1.9'
    expandableLayoutVersion = '2.9.2'
    tapTargetViewVersion = '1.11.0'
    tapTargetViewPromptVersion = '2.7.0'
    archVersion = '1.1.1'
    sendBird = '3.0.72'
    circleImageView = '2.2.0'
    stickyScrollViewItems = '1.1.0'
    customTabs = '27.1.1'
    photoView = '2.1.3'
    zxing = '3.6.0'
    zxingCore = '3.3.0'
    shimmerLayout = '2.1.0'
    sdp = '1.0.6'
    flexBox = '1.0.0'
    exoPlayer = '2.8.4'
    ffMpeg = '0.3.2'
    jCodec = '0.1.9'
    nachosTextView = '1.1.1'
    matisse = '0.5.1'
    jodaTime = '2.10'
    youtubeExtractor = 'master-SNAPSHOT'
    firebaseCore = '16.0.7'
    firebaseAuth = '16.1.0'
    firebaseCrash = '16.2.1'
    firebaseMessaging = '17.4.0'
    firebaseRemoteConfig = '16.3.0'
    firestore = '19.0.1'
    moengage = '9.3.02'
    facebookShimmer = '0.4.0'
    playServiceAds = '17.2.1'
    selectableRoundedVersion = '1.0.1'

    supportDependencies = [
            support             : "com.android.support:support-v4:${supportLibraryVersion}",
            appCompat           : "androidx.appcompat:appcompat:${androidXVersion}",
            coreKotlin          : "androidx.core:core-ktx:${androidXVersion}",
            coroutinesCoreKotlin: "org.jetbrains.kotlinx:kotlinx-coroutines-core:${coroutinesCoreKotlin}",
            design              : "com.android.support:design:${supportLibraryVersion}",
            recyclerView        : "com.android.support:recyclerview-v7:${supportLibraryVersion}",
            cardView            : "com.android.support:cardview-v7:${supportLibraryVersion}",
            constrainLayout     : "com.android.support.constraint:constraint-layout:${constrainLayoutVersion}",
    ]

    archLifecycle = [
            archViewModel     : "android.arch.lifecycle:viewmodel:$archVersion",
            archLiveData      : "android.arch.lifecycle:livedata:$archVersion",
            archExtensions    : "android.arch.lifecycle:extensions:$archVersion",
            archReactiveStream: "android.arch.lifecycle:reactivestreams:$archVersion",
            archCompiler      : "android.arch.lifecycle:compiler:$archVersion",
            archRoom          : "android.arch.persistence.room:runtime:$archVersion",
            archRoomCompiler  : "android.arch.persistence.room:compiler:$archVersion",
            archRoomRxJava2   : "android.arch.persistence.room:rxjava2:$archVersion"
    ]

    libraries = [
            eventBus                  : "org.greenrobot:eventbus:${eventBusVersion}",
            okHttp3                   : "com.squareup.okhttp3:okhttp:${okHttp3Version}",
            okhttp3Logging            : "com.squareup.okhttp3:logging-interceptor:${okHttp3Version}",
            okhttp3UrlConnection      : "com.squareup.okhttp3:okhttp-urlconnection:${okHttp3Version}",
            rxJava2                   : "io.reactivex.rxjava2:rxjava:${rxJava2Version}",
            rxAndroid2                : "io.reactivex.rxjava2:rxandroid:${rxAndroid2Version}",
            retrofit                  : "com.squareup.retrofit2:retrofit:${retrofit2Version}",
            retrofitGson              : "com.squareup.retrofit2:converter-gson:${retrofit2Version}",
            retrofitRx2Adapter        : "com.squareup.retrofit2:adapter-rxjava2:${retrofitRx2AdapterVersion}",
            glide                     : "com.github.bumptech.glide:glide:${glideVersion}",
            glideAnnotation           : "com.github.bumptech.glide:annotations:${glideVersion}",
            glideAnnotationProc       : "com.github.bumptech.glide:compiler:${glideVersion}",
            glideOkHttp3              : "com.github.bumptech.glide:okhttp3-integration:${glideOkHttpVersion}@aar",
            dagger                    : "com.google.dagger:dagger:${daggerVersion}",
            daggerCompiler            : "com.google.dagger:dagger-compiler:${daggerVersion}",
            daggerAndroidSupport      : "com.google.dagger:dagger-android-support:${daggerVersion}",
            koinCore                  : "org.koin:koin-core:${koinVersion}",
            koinAndroid               : "org.koin:koin-android:${koinVersion}",
            koinScope                 : "org.koin:koin-android-scope:${koinVersion}",
            koinViewModel             : "org.koin:koin-android-viewmodel:${koinVersion}",
            gson                      : "com.google.code.gson:gson:${gsonVersion}",
            deeplinkDispatch          : "com.airbnb:deeplinkdispatch:${deepLinkVersion}",
            deeplinkDispatchProcessor : "com.airbnb:deeplinkdispatch-processor:${deepLinkVersion}",
            kotlinJre7                : "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${kotlinVersion}",
            anko                      : "org.jetbrains.anko:anko:${ankoVersion}",
            ankoCommon                : "org.jetbrains.anko:anko-commons:${ankoVersion}",
            multidex                  : "com.android.support:multidex:${multidexVersion}",
            rxBindingPlatform         : "com.jakewharton.rxbinding2:rxbinding:${rxBindingVersion}",
            rxBindingAppCompat        : "com.jakewharton.rxbinding2:rxbinding-appcompat-v7:${rxBindingVersion}",
            rxBindingSupport          : "com.jakewharton.rxbinding2:rxbinding-support-v4:${rxBindingVersion}",
            rxBindingPlatformKotlin   : "com.jakewharton.rxbinding2:rxbinding-kotlin:${rxBindingVersion}",
            rxBindingAppCompatKotlin  : "com.jakewharton.rxbinding2:rxbinding-appcompat-v7-kotlin:${rxBindingVersion}",
            rxBindingSupportKotlin    : "com.jakewharton.rxbinding2:rxbinding-support-v4-kotlin:${rxBindingVersion}",
            googlePlace               : "com.google.android.gms:play-services-places:${playServiceVersion}",
            googleCloudMessagging     : "com.google.android.gms:play-services-gcm:${playServiceVersion}",
            googleBaseClient          : "com.google.android.gms:play-services-base:${playServiceVersion}",
            googleLocation            : "com.google.android.gms:play-services-location:${playServiceVersion}",
            crashlytics               : "com.crashlytics.sdk.android:crashlytics:2.9.1@aar",
            mixpanel                  : "com.mixpanel.android:mixpanel-android:${mixpanelVersion}",
            facebookYearClass         : "com.facebook.device.yearclass:yearclass:2.0.0",
            reactiveLocation          : "pl.charmas.android:android-reactive-location:0.10@aar",
            debugLeakCanary           : "com.squareup.leakcanary:leakcanary-android:${leakCanaryVersion}",
            releaseLeakCanary         : "com.squareup.leakcanary:leakcanary-android-no-op:${leakCanaryVersion}",
            firebaseCore              : "com.google.firebase:firebase-core:${firebaseCore}",
            firebaseAuth              : "com.google.firebase:firebase-auth:${firebaseAuth}",
            firebaseCrash             : "com.google.firebase:firebase-crash:${firebaseCrash}",
            firebaseMessaging         : "com.google.firebase:firebase-messaging:${firebaseMessaging}",
            firebaseRemoteConfig      : "com.google.firebase:firebase-config:${firebaseRemoteConfig}",
            firebaseJobDispatcher     : "com.firebase:firebase-jobdispatcher:${jobDispatcherVersion}",
            firestore                 : "com.google.firebase:firebase-firestore:${firestore}",
            threetenabp               : "com.jakewharton.threetenabp:threetenabp:1.0.5",
            animonStream              : "com.annimon:stream:${animonStreamVersion}",
            expandableLayout          : "net.cachapa.expandablelayout:expandablelayout:${expandableLayoutVersion}",
            tapTargetView             : "com.getkeepsafe.taptargetview:taptargetview:${tapTargetViewVersion}",
            tapTargetViewPrompt       : "uk.co.samuelwall:material-tap-target-prompt:${tapTargetViewPromptVersion}",
            sendBird                  : "com.sendbird.sdk:sendbird-android-sdk:${sendBird}",
            circleImageView           : "de.hdodenhof:circleimageview:${circleImageView}",
            stickyScrollViewItems     : "se.emilsjolander:StickyScrollViewItems:${stickyScrollViewItems}",
            customTabs                : "com.android.support:customtabs:${customTabs}",
            photoView                 : "com.github.chrisbanes:PhotoView:${photoView}",
            zxing                     : "com.journeyapps:zxing-android-embedded:${zxing}",
            zxingCore                 : "com.google.zxing:core:${zxingCore}",
            sdp                       : "com.intuit.sdp:sdp-android:${sdp}",
            flexBox                   : "com.google.android:flexbox:${flexBox}",
            shimmerLayout             : "io.supercharge:shimmerlayout:${shimmerLayout}",
            exoPlayer                 : "com.google.android.exoplayer:exoplayer:${exoPlayer}",
            exoPlayerCore             : "com.google.android.exoplayer:exoplayer-core:${exoPlayer}",
            exoPlayerDash             : "com.google.android.exoplayer:exoplayer-dash:${exoPlayer}",
            exoPlayerHls              : "com.google.android.exoplayer:exoplayer-hls:${exoPlayer}",
            exoPlayerUI               : "com.google.android.exoplayer:exoplayer-ui:${exoPlayer}",
            ffMpeg                    : "com.writingminds:FFmpegAndroid:${ffMpeg}",
            jCodec                    : "org.jcodec:jcodec-android:${jCodec}",
            nachosTextView            : "com.hootsuite.android:nachos:${nachosTextView}",
            matisse                   : "com.zhihu.android:matisse:${matisse}",
            jodaTime                  : "joda-time:joda-time:${jodaTime}",
            youtubeExtractor          : "com.github.HaarigerHarald:android-youtubeExtractor:${youtubeExtractor}",
            moengage                  : "com.moengage:moe-android-sdk:${moengage}",
            googlePlaces              : "com.google.android.libraries.places:places:${googlePlacesVersion}",
            branch                    : "io.branch.sdk.android:library:3.+",
            facebookShimmer           : "com.facebook.shimmer:shimmer:${facebookShimmer}",
            playServiceAds            : "com.google.android.gms:play-services-ads:${playServiceAds}",
            selectableRoundedImageView: "com.joooonho:selectableroundedimageview:${selectableRoundedVersion}"
    ]

    testSupportDependencies = [
            espressoCore          : "com.android.support.test.espresso:espresso-core:${espressoCoreVersion}",
            espressoIntents       : "com.android.support.test.espresso:espresso-intents:${espressoCoreVersion}",
            espressoContrib       : "com.android.support.test.espresso:espresso-contrib:${espressoCoreVersion}",
            espressoIdlingResource: "com.android.support.test.espresso:espresso-idling-resource:${espressoCoreVersion}"
    ]

    testLibraries = [
            junit                    : "junit:junit:4.12",
            mockitoCore              : "org.mockito:mockito-core:2.13.0",
            dexMakerMockito          : "com.google.dexmaker:dexmaker-mockito:1.2",
            mockWebServer3           : "com.squareup.okhttp3:mockwebserver:3.9.1",
            leakcanaryTestCompileNoOp: "com.squareup.leakcanary:leakcanary-android-no-op:${leakCanaryVersion}",
            powerMockJUnit           : "org.powermock:powermock-module-junit4:${powerMockVersion}",
            powerMockMockito         : "org.powermock:powermock-api-mockito:${powerMockVersion}",
            mockitoInline            : "org.mockito:mockito-inline:2.13.0",
            mockitoKotlin            : "com.nhaarman:mockito-kotlin:1.5.0",
            robolectric              : "org.robolectric:robolectric:3.6.1",
            kotlin_reflect           : "org.jetbrains.kotlin:kotlin-reflect:$kotlinVersion",
            koinTest                 : "org.koin:koin-test:${koinVersion}"
    ]

}
