pluginManagement {
    repositories {
        google()
        jcenter()
        mavenCentral()
        gradlePluginPortal()

    }

}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}

rootProject.name='Tahlil'
include ':app'

// Core modules
include ':core:core-ui'
include ':core:core-data'
include ':core:core-firebase'
include ':core:core-common'

// Feature modules
include ':feature:feature-tasbeeh'
include ':feature:feature-memorial'
include ':feature:feature-community'
include ':feature:feature-auth'

// Shared modules
include ':shared:shared-preferences'
include ':shared:shared-analytics'
include ':shared:shared-resources'