apply plugin: 'com.android.application'

android {
    signingConfigs {
        debug {
            storePassword "almulk2024"
            keyAlias 'almulk-debug-key'
            keyPassword 'almulk2024'
            storeFile file("debug-key.jks")
        }
        release {
            storePassword "almulk2024"
            keyAlias 'almulk-release-key'
            keyPassword 'almulk2024'
            storeFile file('release-key.jks')
        }
    }
}
