android {
    signingConfigs {
        debug {
            storePassword "yasin2025"
            keyAlias 'yasin-debug-key'
            keyPassword 'yasin2025'
            storeFile file("debug-key.jks")
        }
        release {
            storePassword "yasin2025"
            keyAlias 'yasin-release-key'
            keyPassword 'yasin2025'
            storeFile file('release-key.jks')
        }
    }
}