plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.devtools.ksp'
    id("com.google.firebase.crashlytics")
    id 'com.google.gms.google-services'
}

ext.majorVersion = 1
ext.minorVersion = 0
ext.patchVersion = 4
ext.preRelease = ""

apply from: '../sign.gradle'
apply from: "../dependencies.gradle"
apply from: '../variant_filter.gradle'

ext {
    buildToolsVersion = "30.0.0"
    minSdkVersion = 24
    targetSdkVersion = 34
    compileSdkVersion = 34
}

android {
    compileSdk = 34
    defaultConfig {
        applicationId "com.quran.surah_almulk"
        minSdk project.ext.minSdkVersion
        targetSdk project.ext.targetSdkVersion
        versionCode generateVersionCode()
        versionName generateVersionName()
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
            testCoverageEnabled = true
            minifyEnabled false
            debuggable true
        }
        release {
            signingConfig signingConfigs.release
            debuggable false
            minifyEnabled true
            shrinkResources true
            crunchPngs true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        viewBinding true
        dataBinding true
        buildConfig true
    }
    flavorDimensions "env"
    productFlavors {
        production {
            dimension "env"
            applicationId "com.quran.surah_almulk"
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }

    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "AlMulk-${generateVersionName()}-${variant.flavorName}-${variant.buildType.name}.apk"
        }
    }
    namespace 'com.quran.surah_almulk'
}

apply from: '../variant_filter.gradle'

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.aar'])
    implementation 'androidx.appcompat:appcompat:1.7.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
    implementation group: 'org.jacoco', name: 'org.jacoco.agent', version: '0.8.8'

    //Android Support Dependencies
    implementation supportDependencies.appCompat
    implementation supportDependencies.coreKotlin
    implementation supportDependencies.coroutinesCoreKotlin
    implementation supportDependencies.design
    implementation supportDependencies.cardView
    implementation libraries.multidex
    implementation libraries.gson

    //Ads
    implementation("com.google.android.gms:play-services-ads:23.3.0")


    //Dependency Injection
    implementation("io.insert-koin:koin-android:3.4.3")

    //Rx
    implementation libraries.rxJava2
    implementation libraries.rxAndroid2
    implementation libraries.rxBindingPlatform
    implementation libraries.rxBindingAppCompat
    implementation libraries.rxBindingSupport
    implementation libraries.rxBindingAppCompatKotlin
    implementation libraries.rxBindingPlatformKotlin
    implementation libraries.rxBindingSupportKotlin

    //Glide
    implementation libraries.glide

    //Architecture Component
    implementation("androidx.room:room-runtime:2.6.1")
    implementation "android.arch.persistence.room:rxjava2:1.1.1"
    implementation 'androidx.room:room-ktx:2.6.1'
    ksp "androidx.room:room-compiler:2.6.1"

    implementation "android.arch.lifecycle:extensions:1.1.1"
    implementation "android.arch.lifecycle:compiler:1.1.1"
    implementation "androidx.paging:paging-runtime:3.2.1"

    // Lifecycle components
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.4"
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:2.8.4"
    implementation "androidx.lifecycle:lifecycle-common-java8:2.8.4"

    // Kotlin components
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.70"
    api "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.1"
    api "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.4.1"

    // UI
    implementation "androidx.constraintlayout:constraintlayout:2.1.4"
    implementation "com.google.android.material:material:1.6.0"
//    implementation 'com.google.android.material:material:1.6.0'
    implementation "androidx.viewpager2:viewpager2:1.1.0"
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.recyclerview:recyclerview:1.2.1'

    // Tap target view
    implementation 'uk.co.samuelwall:material-tap-target-prompt:3.3.2'

    // Testing
    testImplementation "junit:junit:4.13.2"
    androidTestImplementation "androidx.arch.core:core-testing:2.2.0"
    androidTestImplementation("androidx.test.espresso:espresso-core:1.0.0", {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    androidTestImplementation "androidx.test.ext:junit:1.1.5"

    implementation 'androidx.work:work-runtime-ktx:2.9.0'

    // Import the BoM for the Firebase platform
    implementation(platform("com.google.firebase:firebase-bom:33.1.2"))
    implementation("com.google.firebase:firebase-config")
    implementation("com.google.firebase:firebase-crashlytics")
    implementation("com.google.firebase:firebase-database")
    implementation("com.google.android.play:review-ktx:2.0.2")
    implementation("com.google.firebase:firebase-analytics")

    //Expandable Layout
    implementation "com.github.skydoves:expandablelayout:1.0.7"
}

private Integer generateVersionCode() {
    return project.ext.minSdkVersion * 10000000 + ext.majorVersion * 10000 + ext.minorVersion * 100 + ext.patchVersion
}

private String generateVersionName() {
    String versionName = "${ext.majorVersion}.${ext.minorVersion}.${ext.patchVersion}"
    return versionName
}

apply plugin: 'com.google.firebase.crashlytics'